### ISSUE TITLE
Upload logo

### ISSUE THREAD

**Issue by rajasekhar-gundala** [jammeryhq/gridsome-starter-liebling#1]
Thanks a lot for the great project. I wanted to customize the site, upload logo and edit links in footer and footer color. Also reduce the footer padding.

Please let me know the steps for the same.

**Comment by noxify** [comment]
Hi @rajaseg,

You can change the links for the header and footer in this file:
https://github.com/jammeryhq/gridsome-starter-liebling/blob/master/content/site/navigation.json

To change the padding/color in the footer, you have to edit the following file:
https://github.com/jammeryhq/gridsome-starter-liebling/blob/master/src/components/Partials/Footer.vue

Hope that helps.
