### ISSUE TITLE
replace node-sass with dart-sass

### ISSUE THREAD

**Issue by datadu-de** [jammeryhq/gridsome-starter-liebling#17]
use of `node-sass` is deprecated since 2020, replacement with `dart-sass` is recommended.
Also node-sass requires python 2.7, which end-of-life was in 2020.
I tried to implement this myself and create a pull-request but I'm unfortunately not proficient enough.
Would be amazing if someone could look into this.

This issue is also valid for the other starters that have node-sass in the dependencies.

**Comment by noxify** [comment]
Hi @datadu-de 

i have updated the template and fixed all fixable issues

There are some audits which I can't fix from our side.

There are also some issues with some packages like twbs/rfs.
I'm currently using a local file which fixs the deprecated warnings for now.

There are also some changes in the `gridsome.config.js` and the `SearchModal.vue` to fix some issues after upgrading to the latest flexsearch version.

I will try to fix the other templates as soon as I can ✌️

I have tested it only locally but everything worked as expected.

**Comment by datadu-de** [comment]
@noxify wow that was quick :-)
thanks a lot! 👍
