### ISSUE TITLE
Vue Infinite Load

### ISSUE THREAD

**Issue by SupremeSalvatore** [jammeryhq/gridsome-starter-liebling#6]
I can see that there is a infinity load component, however nowhere in readme is described usability of it.
It would be benefitial that there is an example or better documentation how to implement it along graphql queries.

**Comment by zbrkic** [comment]
Example: https://liebling.jammeryhq.com/infinity
Detail explanation: https://gridsome.org/blog/2019/10/08/infinite-loading-with-gridsome/

**Comment by SupremeSalvatore** [comment]
Thanks Zeljko, I managed to implement this, I will close Issue.
